import type { Metadata } from "next";
import { Poppins, Gorditas } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/global/theme";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});
const gorditas = Gorditas({
  subsets: ["latin"],
  weight: ["400", "700"], // Gorditas is only available in Regular (400) and Bold (700)
  variable: "--font-gorditas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${gorditas.variable} font-[Poppins] antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
